apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: debezium-kafka-connect-cluster
  name: target-connector
spec:
  class: io.debezium.connector.jdbc.JdbcSinkConnector
  config:
    topics: debezium.InternationalDB.dbo.Customers
    connection.url: jdbc:sqlserver://target-mssql:1433;databaseName=InternationalDB;encrypt=false
    connection.username: sa
    connection.password: Password!
    insert.mode: upsert
    delete.enabled: "true"
    primary.key.mode: record_key
    primary.key.fields: id
    schema.evolution: basic
    errors.log.enable: "true"
    table.name.format: "${source.schema}.${source.table}"
  tasksMax: 1
